<%@ Page Title="Home" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="EjemploSiteMapPath.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="App_Themes/Default/Texto.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Home</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dignissim turpis vitae leo dapibus in facilisis sapien cursus. In sed sapien sit amet risus scelerisque feugiat id in lectus. Fusce interdum tincidunt dignissim. Donec nec dolor nec lorem auctor pellentesque. Vestibulum ac justo sit amet dui consectetur posuere. Cras mattis consequat vestibulum. Proin ac ligula vitae mi pretium commodo et vel purus.</p>
    <h2>Lorem Impsum</h2>
    <p>Cras lacinia sagittis purus sed condimentum. Praesent non consectetur tortor. Nulla nec ipsum magna, sit amet gravida orci. Quisque ac velit eu eros faucibus facilisis. Quisque et nulla at quam auctor rhoncus. Proin aliquet accumsan diam, sit amet gravida dui feugiat et. Integer dignissim neque sit amet dui accumsan sit amet imperdiet justo eleifend. Phasellus ut eros augue. Aliquam elit mauris, condimentum eleifend facilisis vel, vulputate et lorem. Suspendisse sed lectus sit amet felis commodo egestas non quis arcu. Sed aliquam tellus id dolor dignissim at gravida nisi sagittis.</p>
    <p>Nam nec nunc vel risus pharetra facilisis. Quisque ac imperdiet mi. Proin at arcu ligula, ut hendrerit odio. Donec vitae varius purus. Phasellus eros arcu, porta sit amet iaculis quis, accumsan vitae nunc. Sed imperdiet nisl ac ligula molestie a euismod dolor ornare. Etiam posuere luctus risus et vulputate. Nunc sit amet odio id urna pretium pellentesque et sit amet ligula. Aenean velit enim, rhoncus sit amet adipiscing placerat, ultricies a magna. Donec euismod faucibus lacus, at vehicula libero volutpat id.</p>
    <p>Nullam facilisis ipsum aliquam eros ullamcorper vulputate. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi rutrum tempus vulputate. Fusce tellus turpis, lobortis quis fermentum nec, egestas a ante. Nulla sodales sodales suscipit. Sed dignissim porttitor lacus eleifend varius. Vestibulum consequat, dui at mattis vestibulum, sapien nibh pellentesque arcu, sit amet faucibus mi lacus eget urna.</p>
    <p>Duis sollicitudin magna sed turpis laoreet vel feugiat ligula placerat. Nam volutpat, mi at interdum porta, sem arcu ornare ligula, nec accumsan arcu libero et arcu. Vestibulum ac lorem odio, eu pharetra tortor. Nullam tincidunt, lectus quis rutrum egestas, magna lorem elementum ligula, eget cursus augue magna at augue. Proin porta est at nibh eleifend imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut interdum quam.</p>
</asp:Content>
