//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCurso.srServicioCursoBD {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srServicioCursoBD.ServicioCursoBDSoap")]
    public interface ServicioCursoBDSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPais", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TraerPais(int pIdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPais", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TraerPaisAsync(int pIdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductosxCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ProductosxCategoria(int pIdCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductosxCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ProductosxCategoriaAsync(int pIdCategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCursoBDSoapChannel : WebCurso.srServicioCursoBD.ServicioCursoBDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCursoBDSoapClient : System.ServiceModel.ClientBase<WebCurso.srServicioCursoBD.ServicioCursoBDSoap>, WebCurso.srServicioCursoBD.ServicioCursoBDSoap {
        
        public ServicioCursoBDSoapClient() {
        }
        
        public ServicioCursoBDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCursoBDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoBDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoBDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TraerPais(int pIdCliente) {
            return base.Channel.TraerPais(pIdCliente);
        }
        
        public System.Threading.Tasks.Task<string> TraerPaisAsync(int pIdCliente) {
            return base.Channel.TraerPaisAsync(pIdCliente);
        }
        
        public System.Data.DataSet ProductosxCategoria(int pIdCategoria) {
            return base.Channel.ProductosxCategoria(pIdCategoria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ProductosxCategoriaAsync(int pIdCategoria) {
            return base.Channel.ProductosxCategoriaAsync(pIdCategoria);
        }
    }
}
